formatter: markdown table
output:
  file: "./README.md"
  mode: replace
  template: |-
    [![Terraform](https://github.com/Smartbrood/terraform-aws-lambda/actions/workflows/terraform-validate-apply.yml/badge.svg)](https://github.com/Smartbrood/terraform-aws-lambda/actions/workflows/terraform-validate-apply.yml)
    # terraform-aws-lambda

    Terraform module to create AWS Lambda based on docker image.

    ## Usage
    ```
    module "lambda" {
      source                  = "Smartbrood/lambda/aws"
      version                 = "1.0.1"
      name                    = "my-lambda"
      aws_ecr_repository_name = "my-ecr-repo"
      image_tag               = "latest"
      memory_size             = "128"
      timeout                 = "60"
      architectures           = ["x86_64"]
    }
    ```

    {{ .Content }}

sections:
  hide-all: true
  show:
    - header
    - inputs
    - outputs
    - providers
    - resources

sort:
  enabled: true
  by: required