name: Terraform

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: "test"
  AWS_ACCOUNT_ID: 904317604667
  AWS_REGION: "eu-west-1"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Terraform validate
      run: |
        make validate
  apply-and-destroy:
    runs-on: ubuntu-latest
    needs: validate
    defaults:
      run:
        working-directory: tests
    strategy:
      max-parallel: 4
      matrix:
        timeout: [1, 900]
        memory_size: [128, 10240]
    env:
      TF_VAR_timeout: ${{ matrix.timeout }}
      TF_VAR_memory_size: ${{ matrix.memory_size }}
      TF_WORKSPACE: matrix_${{ matrix.timeout }}_${{ matrix.memory_size }}
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/my-github-actions-role
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHubActions
    - name: Version
      run: terraform version
    - name: Workspace
      run: terraform workspace new $TF_WORKSPACE
    - name: Init
      run: terraform init -input=false
    - name: Apply
      run: terraform apply -input=false -auto-approve
    - name: Check Apply
      run: terraform plan -input=false -detailed-exitcode
    - name: Output
      run: terraform output -json
    - name: Destroy
      run: terraform destroy -input=false -auto-approve
    - name: Check Destroy
      run: terraform plan -destroy -input=false -detailed-exitcode
